// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: src/lib/simulation.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DistributionType int32

const (
	DistributionType_DISTRIBUTION_TYPE_UNSPECIFIED DistributionType = 0
	DistributionType_DISTRIBUTION_TYPE_NORMAL      DistributionType = 1
	DistributionType_DISTRIBUTION_TYPE_UNIFORM     DistributionType = 2
	DistributionType_DISTRIBUTION_TYPE_CONSTANT    DistributionType = 3
)

// Enum value maps for DistributionType.
var (
	DistributionType_name = map[int32]string{
		0: "DISTRIBUTION_TYPE_UNSPECIFIED",
		1: "DISTRIBUTION_TYPE_NORMAL",
		2: "DISTRIBUTION_TYPE_UNIFORM",
		3: "DISTRIBUTION_TYPE_CONSTANT",
	}
	DistributionType_value = map[string]int32{
		"DISTRIBUTION_TYPE_UNSPECIFIED": 0,
		"DISTRIBUTION_TYPE_NORMAL":      1,
		"DISTRIBUTION_TYPE_UNIFORM":     2,
		"DISTRIBUTION_TYPE_CONSTANT":    3,
	}
)

func (x DistributionType) Enum() *DistributionType {
	p := new(DistributionType)
	*p = x
	return p
}

func (x DistributionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DistributionType) Descriptor() protoreflect.EnumDescriptor {
	return file_src_lib_simulation_proto_enumTypes[0].Descriptor()
}

func (DistributionType) Type() protoreflect.EnumType {
	return &file_src_lib_simulation_proto_enumTypes[0]
}

func (x DistributionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DistributionType.Descriptor instead.
func (DistributionType) EnumDescriptor() ([]byte, []int) {
	return file_src_lib_simulation_proto_rawDescGZIP(), []int{0}
}

type ConditionOperator int32

const (
	ConditionOperator_CONDITION_OPERATOR_UNSPECIFIED ConditionOperator = 0
	ConditionOperator_CONDITION_OPERATOR_EQ          ConditionOperator = 1
	ConditionOperator_CONDITION_OPERATOR_NEQ         ConditionOperator = 2
	ConditionOperator_CONDITION_OPERATOR_GT          ConditionOperator = 3
	ConditionOperator_CONDITION_OPERATOR_LT          ConditionOperator = 4
	ConditionOperator_CONDITION_OPERATOR_GTE         ConditionOperator = 5
	ConditionOperator_CONDITION_OPERATOR_LTE         ConditionOperator = 6
)

// Enum value maps for ConditionOperator.
var (
	ConditionOperator_name = map[int32]string{
		0: "CONDITION_OPERATOR_UNSPECIFIED",
		1: "CONDITION_OPERATOR_EQ",
		2: "CONDITION_OPERATOR_NEQ",
		3: "CONDITION_OPERATOR_GT",
		4: "CONDITION_OPERATOR_LT",
		5: "CONDITION_OPERATOR_GTE",
		6: "CONDITION_OPERATOR_LTE",
	}
	ConditionOperator_value = map[string]int32{
		"CONDITION_OPERATOR_UNSPECIFIED": 0,
		"CONDITION_OPERATOR_EQ":          1,
		"CONDITION_OPERATOR_NEQ":         2,
		"CONDITION_OPERATOR_GT":          3,
		"CONDITION_OPERATOR_LT":          4,
		"CONDITION_OPERATOR_GTE":         5,
		"CONDITION_OPERATOR_LTE":         6,
	}
)

func (x ConditionOperator) Enum() *ConditionOperator {
	p := new(ConditionOperator)
	*p = x
	return p
}

func (x ConditionOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConditionOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_src_lib_simulation_proto_enumTypes[1].Descriptor()
}

func (ConditionOperator) Type() protoreflect.EnumType {
	return &file_src_lib_simulation_proto_enumTypes[1]
}

func (x ConditionOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConditionOperator.Descriptor instead.
func (ConditionOperator) EnumDescriptor() ([]byte, []int) {
	return file_src_lib_simulation_proto_rawDescGZIP(), []int{1}
}

type DeviceCategory int32

const (
	DeviceCategory_DEVICE_CATEGORY_UNSPECIFIED   DeviceCategory = 0
	DeviceCategory_DEVICE_CATEGORY_COOKING       DeviceCategory = 1
	DeviceCategory_DEVICE_CATEGORY_HEATING       DeviceCategory = 2
	DeviceCategory_DEVICE_CATEGORY_COLD_STORAGE  DeviceCategory = 3
	DeviceCategory_DEVICE_CATEGORY_LIGHTING      DeviceCategory = 4
	DeviceCategory_DEVICE_CATEGORY_WET_APPLIANCE DeviceCategory = 5
	DeviceCategory_DEVICE_CATEGORY_ELECTRONICS   DeviceCategory = 6
	DeviceCategory_DEVICE_CATEGORY_BASE_LOAD     DeviceCategory = 7
)

// Enum value maps for DeviceCategory.
var (
	DeviceCategory_name = map[int32]string{
		0: "DEVICE_CATEGORY_UNSPECIFIED",
		1: "DEVICE_CATEGORY_COOKING",
		2: "DEVICE_CATEGORY_HEATING",
		3: "DEVICE_CATEGORY_COLD_STORAGE",
		4: "DEVICE_CATEGORY_LIGHTING",
		5: "DEVICE_CATEGORY_WET_APPLIANCE",
		6: "DEVICE_CATEGORY_ELECTRONICS",
		7: "DEVICE_CATEGORY_BASE_LOAD",
	}
	DeviceCategory_value = map[string]int32{
		"DEVICE_CATEGORY_UNSPECIFIED":   0,
		"DEVICE_CATEGORY_COOKING":       1,
		"DEVICE_CATEGORY_HEATING":       2,
		"DEVICE_CATEGORY_COLD_STORAGE":  3,
		"DEVICE_CATEGORY_LIGHTING":      4,
		"DEVICE_CATEGORY_WET_APPLIANCE": 5,
		"DEVICE_CATEGORY_ELECTRONICS":   6,
		"DEVICE_CATEGORY_BASE_LOAD":     7,
	}
)

func (x DeviceCategory) Enum() *DeviceCategory {
	p := new(DeviceCategory)
	*p = x
	return p
}

func (x DeviceCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_src_lib_simulation_proto_enumTypes[2].Descriptor()
}

func (DeviceCategory) Type() protoreflect.EnumType {
	return &file_src_lib_simulation_proto_enumTypes[2]
}

func (x DeviceCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceCategory.Descriptor instead.
func (DeviceCategory) EnumDescriptor() ([]byte, []int) {
	return file_src_lib_simulation_proto_rawDescGZIP(), []int{2}
}

type ProfileType int32

const (
	ProfileType_PROFILE_TYPE_UNSPECIFIED ProfileType = 0
	ProfileType_PROFILE_TYPE_CONSTANT    ProfileType = 1
	ProfileType_PROFILE_TYPE_CYCLIC      ProfileType = 2 // e.g., Fridge compressor
	ProfileType_PROFILE_TYPE_VARIABLE    ProfileType = 3 // e.g., Washing machine cycles
)

// Enum value maps for ProfileType.
var (
	ProfileType_name = map[int32]string{
		0: "PROFILE_TYPE_UNSPECIFIED",
		1: "PROFILE_TYPE_CONSTANT",
		2: "PROFILE_TYPE_CYCLIC",
		3: "PROFILE_TYPE_VARIABLE",
	}
	ProfileType_value = map[string]int32{
		"PROFILE_TYPE_UNSPECIFIED": 0,
		"PROFILE_TYPE_CONSTANT":    1,
		"PROFILE_TYPE_CYCLIC":      2,
		"PROFILE_TYPE_VARIABLE":    3,
	}
)

func (x ProfileType) Enum() *ProfileType {
	p := new(ProfileType)
	*p = x
	return p
}

func (x ProfileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProfileType) Descriptor() protoreflect.EnumDescriptor {
	return file_src_lib_simulation_proto_enumTypes[3].Descriptor()
}

func (ProfileType) Type() protoreflect.EnumType {
	return &file_src_lib_simulation_proto_enumTypes[3]
}

func (x ProfileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProfileType.Descriptor instead.
func (ProfileType) EnumDescriptor() ([]byte, []int) {
	return file_src_lib_simulation_proto_rawDescGZIP(), []int{3}
}

type TriggerType int32

const (
	TriggerType_TRIGGER_TYPE_UNSPECIFIED    TriggerType = 0
	TriggerType_TRIGGER_TYPE_TIME_OF_DAY    TriggerType = 1
	TriggerType_TRIGGER_TYPE_EVENT_REACTION TriggerType = 2
)

// Enum value maps for TriggerType.
var (
	TriggerType_name = map[int32]string{
		0: "TRIGGER_TYPE_UNSPECIFIED",
		1: "TRIGGER_TYPE_TIME_OF_DAY",
		2: "TRIGGER_TYPE_EVENT_REACTION",
	}
	TriggerType_value = map[string]int32{
		"TRIGGER_TYPE_UNSPECIFIED":    0,
		"TRIGGER_TYPE_TIME_OF_DAY":    1,
		"TRIGGER_TYPE_EVENT_REACTION": 2,
	}
)

func (x TriggerType) Enum() *TriggerType {
	p := new(TriggerType)
	*p = x
	return p
}

func (x TriggerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerType) Descriptor() protoreflect.EnumDescriptor {
	return file_src_lib_simulation_proto_enumTypes[4].Descriptor()
}

func (TriggerType) Type() protoreflect.EnumType {
	return &file_src_lib_simulation_proto_enumTypes[4]
}

func (x TriggerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerType.Descriptor instead.
func (TriggerType) EnumDescriptor() ([]byte, []int) {
	return file_src_lib_simulation_proto_rawDescGZIP(), []int{4}
}

type DeviceState int32

const (
	DeviceState_DEVICE_STATE_UNSPECIFIED DeviceState = 0
	DeviceState_DEVICE_STATE_ON          DeviceState = 1
	DeviceState_DEVICE_STATE_OFF         DeviceState = 2
	DeviceState_DEVICE_STATE_STANDBY     DeviceState = 3
)

// Enum value maps for DeviceState.
var (
	DeviceState_name = map[int32]string{
		0: "DEVICE_STATE_UNSPECIFIED",
		1: "DEVICE_STATE_ON",
		2: "DEVICE_STATE_OFF",
		3: "DEVICE_STATE_STANDBY",
	}
	DeviceState_value = map[string]int32{
		"DEVICE_STATE_UNSPECIFIED": 0,
		"DEVICE_STATE_ON":          1,
		"DEVICE_STATE_OFF":         2,
		"DEVICE_STATE_STANDBY":     3,
	}
)

func (x DeviceState) Enum() *DeviceState {
	p := new(DeviceState)
	*p = x
	return p
}

func (x DeviceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceState) Descriptor() protoreflect.EnumDescriptor {
	return file_src_lib_simulation_proto_enumTypes[5].Descriptor()
}

func (DeviceState) Type() protoreflect.EnumType {
	return &file_src_lib_simulation_proto_enumTypes[5]
}

func (x DeviceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceState.Descriptor instead.
func (DeviceState) EnumDescriptor() ([]byte, []int) {
	return file_src_lib_simulation_proto_rawDescGZIP(), []int{5}
}

type EngineCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextKey    string                 `protobuf:"bytes,1,opt,name=context_key,json=contextKey,proto3" json:"context_key,omitempty"` // e.g., "weather.external_temp_c", "time.is_weekend"
	Operator      ConditionOperator      `protobuf:"varint,2,opt,name=operator,proto3,enum=simulation.v1.ConditionOperator" json:"operator,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"` // String representation, parsed by the Go engine
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineCondition) Reset() {
	*x = EngineCondition{}
	mi := &file_src_lib_simulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineCondition) ProtoMessage() {}

func (x *EngineCondition) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_simulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineCondition.ProtoReflect.Descriptor instead.
func (*EngineCondition) Descriptor() ([]byte, []int) {
	return file_src_lib_simulation_proto_rawDescGZIP(), []int{0}
}

func (x *EngineCondition) GetContextKey() string {
	if x != nil {
		return x.ContextKey
	}
	return ""
}

func (x *EngineCondition) GetOperator() ConditionOperator {
	if x != nil {
		return x.Operator
	}
	return ConditionOperator_CONDITION_OPERATOR_UNSPECIFIED
}

func (x *EngineCondition) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DistributionModifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Condition     *EngineCondition       `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	ShiftMean     string                 `protobuf:"bytes,2,opt,name=shift_mean,json=shiftMean,proto3" json:"shift_mean,omitempty"`    // e.g., "+30m"
	ShiftValue    string                 `protobuf:"bytes,3,opt,name=shift_value,json=shiftValue,proto3" json:"shift_value,omitempty"` // e.g., "*1.2"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistributionModifier) Reset() {
	*x = DistributionModifier{}
	mi := &file_src_lib_simulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributionModifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributionModifier) ProtoMessage() {}

func (x *DistributionModifier) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_simulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributionModifier.ProtoReflect.Descriptor instead.
func (*DistributionModifier) Descriptor() ([]byte, []int) {
	return file_src_lib_simulation_proto_rawDescGZIP(), []int{1}
}

func (x *DistributionModifier) GetCondition() *EngineCondition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *DistributionModifier) GetShiftMean() string {
	if x != nil {
		return x.ShiftMean
	}
	return ""
}

func (x *DistributionModifier) GetShiftValue() string {
	if x != nil {
		return x.ShiftValue
	}
	return ""
}

type ProbabilityDistribution struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          DistributionType        `protobuf:"varint,1,opt,name=type,proto3,enum=simulation.v1.DistributionType" json:"type,omitempty"`
	Value         string                  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`                 // For constant (e.g., "1.5")
	Mean          string                  `protobuf:"bytes,3,opt,name=mean,proto3" json:"mean,omitempty"`                   // For normal (e.g., "07:30" or "45")
	StdDev        string                  `protobuf:"bytes,4,opt,name=std_dev,json=stdDev,proto3" json:"std_dev,omitempty"` // For normal (e.g., "15m" or "5")
	Min           float64                 `protobuf:"fixed64,5,opt,name=min,proto3" json:"min,omitempty"`                   // For uniform
	Max           float64                 `protobuf:"fixed64,6,opt,name=max,proto3" json:"max,omitempty"`                   // For uniform
	Modifiers     []*DistributionModifier `protobuf:"bytes,7,rep,name=modifiers,proto3" json:"modifiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbabilityDistribution) Reset() {
	*x = ProbabilityDistribution{}
	mi := &file_src_lib_simulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbabilityDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbabilityDistribution) ProtoMessage() {}

func (x *ProbabilityDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_simulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbabilityDistribution.ProtoReflect.Descriptor instead.
func (*ProbabilityDistribution) Descriptor() ([]byte, []int) {
	return file_src_lib_simulation_proto_rawDescGZIP(), []int{2}
}

func (x *ProbabilityDistribution) GetType() DistributionType {
	if x != nil {
		return x.Type
	}
	return DistributionType_DISTRIBUTION_TYPE_UNSPECIFIED
}

func (x *ProbabilityDistribution) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ProbabilityDistribution) GetMean() string {
	if x != nil {
		return x.Mean
	}
	return ""
}

func (x *ProbabilityDistribution) GetStdDev() string {
	if x != nil {
		return x.StdDev
	}
	return ""
}

func (x *ProbabilityDistribution) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *ProbabilityDistribution) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *ProbabilityDistribution) GetModifiers() []*DistributionModifier {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

type FatigueRule struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LockoutDuration   string                 `protobuf:"bytes,1,opt,name=lockout_duration,json=lockoutDuration,proto3" json:"lockout_duration,omitempty"`         // e.g., "30m" (Hard block before it can run again)
	RecoveryDuration  string                 `protobuf:"bytes,2,opt,name=recovery_duration,json=recoveryDuration,proto3" json:"recovery_duration,omitempty"`      // e.g., "2h" (Gradual return to normal probability)
	PenaltyMultiplier float64                `protobuf:"fixed64,3,opt,name=penalty_multiplier,json=penaltyMultiplier,proto3" json:"penalty_multiplier,omitempty"` // e.g., 0.1 (Drops a 50% chance to 5% during recovery)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FatigueRule) Reset() {
	*x = FatigueRule{}
	mi := &file_src_lib_simulation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FatigueRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FatigueRule) ProtoMessage() {}

func (x *FatigueRule) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_simulation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FatigueRule.ProtoReflect.Descriptor instead.
func (*FatigueRule) Descriptor() ([]byte, []int) {
	return file_src_lib_simulation_proto_rawDescGZIP(), []int{3}
}

func (x *FatigueRule) GetLockoutDuration() string {
	if x != nil {
		return x.LockoutDuration
	}
	return ""
}

func (x *FatigueRule) GetRecoveryDuration() string {
	if x != nil {
		return x.RecoveryDuration
	}
	return ""
}

func (x *FatigueRule) GetPenaltyMultiplier() float64 {
	if x != nil {
		return x.PenaltyMultiplier
	}
	return 0
}

type DeviceTaxonomy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      DeviceCategory         `protobuf:"varint,1,opt,name=category,proto3,enum=simulation.v1.DeviceCategory" json:"category,omitempty"`
	ClassName     string                 `protobuf:"bytes,2,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"` // e.g., "fridge_freezer", "kettle", "hvac"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceTaxonomy) Reset() {
	*x = DeviceTaxonomy{}
	mi := &file_src_lib_simulation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceTaxonomy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceTaxonomy) ProtoMessage() {}

func (x *DeviceTaxonomy) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_simulation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceTaxonomy.ProtoReflect.Descriptor instead.
func (*DeviceTaxonomy) Descriptor() ([]byte, []int) {
	return file_src_lib_simulation_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceTaxonomy) GetCategory() DeviceCategory {
	if x != nil {
		return x.Category
	}
	return DeviceCategory_DEVICE_CATEGORY_UNSPECIFIED
}

func (x *DeviceTaxonomy) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type DeviceProfile struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             ProfileType            `protobuf:"varint,1,opt,name=type,proto3,enum=simulation.v1.ProfileType" json:"type,omitempty"`
	MaxWatts         float64                `protobuf:"fixed64,2,opt,name=max_watts,json=maxWatts,proto3" json:"max_watts,omitempty"`
	StandbyWatts     float64                `protobuf:"fixed64,3,opt,name=standby_watts,json=standbyWatts,proto3" json:"standby_watts,omitempty"`
	CooldownDuration string                 `protobuf:"bytes,4,opt,name=cooldown_duration,json=cooldownDuration,proto3" json:"cooldown_duration,omitempty"` // e.g., "5m" - Device lock preventing rapid cycling
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeviceProfile) Reset() {
	*x = DeviceProfile{}
	mi := &file_src_lib_simulation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceProfile) ProtoMessage() {}

func (x *DeviceProfile) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_simulation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceProfile.ProtoReflect.Descriptor instead.
func (*DeviceProfile) Descriptor() ([]byte, []int) {
	return file_src_lib_simulation_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceProfile) GetType() ProfileType {
	if x != nil {
		return x.Type
	}
	return ProfileType_PROFILE_TYPE_UNSPECIFIED
}

func (x *DeviceProfile) GetMaxWatts() float64 {
	if x != nil {
		return x.MaxWatts
	}
	return 0
}

func (x *DeviceProfile) GetStandbyWatts() float64 {
	if x != nil {
		return x.StandbyWatts
	}
	return 0
}

func (x *DeviceProfile) GetCooldownDuration() string {
	if x != nil {
		return x.CooldownDuration
	}
	return ""
}

type DeviceTemplate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeviceId          string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Taxonomy          *DeviceTaxonomy        `protobuf:"bytes,2,opt,name=taxonomy,proto3" json:"taxonomy,omitempty"`
	Specifics         map[string]string      `protobuf:"bytes,3,rep,name=specifics,proto3" json:"specifics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., {"energy_rating": "A", "volume_liters": "1.5"}
	ElectricalProfile *DeviceProfile         `protobuf:"bytes,4,opt,name=electrical_profile,json=electricalProfile,proto3" json:"electrical_profile,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeviceTemplate) Reset() {
	*x = DeviceTemplate{}
	mi := &file_src_lib_simulation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceTemplate) ProtoMessage() {}

func (x *DeviceTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_simulation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceTemplate.ProtoReflect.Descriptor instead.
func (*DeviceTemplate) Descriptor() ([]byte, []int) {
	return file_src_lib_simulation_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceTemplate) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceTemplate) GetTaxonomy() *DeviceTaxonomy {
	if x != nil {
		return x.Taxonomy
	}
	return nil
}

func (x *DeviceTemplate) GetSpecifics() map[string]string {
	if x != nil {
		return x.Specifics
	}
	return nil
}

func (x *DeviceTemplate) GetElectricalProfile() *DeviceProfile {
	if x != nil {
		return x.ElectricalProfile
	}
	return nil
}

type Trigger struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Type           TriggerType              `protobuf:"varint,1,opt,name=type,proto3,enum=simulation.v1.TriggerType" json:"type,omitempty"`
	Distribution   *ProbabilityDistribution `protobuf:"bytes,2,opt,name=distribution,proto3" json:"distribution,omitempty"`
	BaseConditions []*EngineCondition       `protobuf:"bytes,3,rep,name=base_conditions,json=baseConditions,proto3" json:"base_conditions,omitempty"`
	FatigueRule    *FatigueRule             `protobuf:"bytes,4,opt,name=fatigue_rule,json=fatigueRule,proto3" json:"fatigue_rule,omitempty"` // Prevents the "100 kettles" problem
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Trigger) Reset() {
	*x = Trigger{}
	mi := &file_src_lib_simulation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trigger) ProtoMessage() {}

func (x *Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_simulation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trigger.ProtoReflect.Descriptor instead.
func (*Trigger) Descriptor() ([]byte, []int) {
	return file_src_lib_simulation_proto_rawDescGZIP(), []int{7}
}

func (x *Trigger) GetType() TriggerType {
	if x != nil {
		return x.Type
	}
	return TriggerType_TRIGGER_TYPE_UNSPECIFIED
}

func (x *Trigger) GetDistribution() *ProbabilityDistribution {
	if x != nil {
		return x.Distribution
	}
	return nil
}

func (x *Trigger) GetBaseConditions() []*EngineCondition {
	if x != nil {
		return x.BaseConditions
	}
	return nil
}

func (x *Trigger) GetFatigueRule() *FatigueRule {
	if x != nil {
		return x.FatigueRule
	}
	return nil
}

type ScenarioAction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceId       string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	State          DeviceState            `protobuf:"varint,2,opt,name=state,proto3,enum=simulation.v1.DeviceState" json:"state,omitempty"`
	DelayFromStart string                 `protobuf:"bytes,3,opt,name=delay_from_start,json=delayFromStart,proto3" json:"delay_from_start,omitempty"` // e.g., "5m"
	// Variables the Go physics engine needs (duration_minutes, water_volume_ml, etc.)
	Parameters    map[string]*ProbabilityDistribution `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioAction) Reset() {
	*x = ScenarioAction{}
	mi := &file_src_lib_simulation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioAction) ProtoMessage() {}

func (x *ScenarioAction) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_simulation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioAction.ProtoReflect.Descriptor instead.
func (*ScenarioAction) Descriptor() ([]byte, []int) {
	return file_src_lib_simulation_proto_rawDescGZIP(), []int{8}
}

func (x *ScenarioAction) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ScenarioAction) GetState() DeviceState {
	if x != nil {
		return x.State
	}
	return DeviceState_DEVICE_STATE_UNSPECIFIED
}

func (x *ScenarioAction) GetDelayFromStart() string {
	if x != nil {
		return x.DelayFromStart
	}
	return ""
}

func (x *ScenarioAction) GetParameters() map[string]*ProbabilityDistribution {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ScenarioTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"` // The intentional human actor driving this
	Trigger       *Trigger               `protobuf:"bytes,3,opt,name=trigger,proto3" json:"trigger,omitempty"`
	Actions       []*ScenarioAction      `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioTemplate) Reset() {
	*x = ScenarioTemplate{}
	mi := &file_src_lib_simulation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioTemplate) ProtoMessage() {}

func (x *ScenarioTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_simulation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioTemplate.ProtoReflect.Descriptor instead.
func (*ScenarioTemplate) Descriptor() ([]byte, []int) {
	return file_src_lib_simulation_proto_rawDescGZIP(), []int{9}
}

func (x *ScenarioTemplate) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *ScenarioTemplate) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ScenarioTemplate) GetTrigger() *Trigger {
	if x != nil {
		return x.Trigger
	}
	return nil
}

func (x *ScenarioTemplate) GetActions() []*ScenarioAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type ActorTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // e.g., "parent_1", "student"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorTemplate) Reset() {
	*x = ActorTemplate{}
	mi := &file_src_lib_simulation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorTemplate) ProtoMessage() {}

func (x *ActorTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_simulation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorTemplate.ProtoReflect.Descriptor instead.
func (*ActorTemplate) Descriptor() ([]byte, []int) {
	return file_src_lib_simulation_proto_rawDescGZIP(), []int{10}
}

func (x *ActorTemplate) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ActorTemplate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type NodeArchetype struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ArchetypeId string                 `protobuf:"bytes,1,opt,name=archetype_id,json=archetypeId,proto3" json:"archetype_id,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Thermodynamic Properties for State-Driven Heating Models
	BaseTempC           float64             `protobuf:"fixed64,3,opt,name=base_temp_c,json=baseTempC,proto3" json:"base_temp_c,omitempty"`                               // Unheated resting temp (driven by weather)
	InsulationDecayRate float64             `protobuf:"fixed64,4,opt,name=insulation_decay_rate,json=insulationDecayRate,proto3" json:"insulation_decay_rate,omitempty"` // Heat loss per hour (e.g., 0.1 for good, 0.5 for drafty)
	Actors              []*ActorTemplate    `protobuf:"bytes,5,rep,name=actors,proto3" json:"actors,omitempty"`
	Devices             []*DeviceTemplate   `protobuf:"bytes,6,rep,name=devices,proto3" json:"devices,omitempty"`
	Scenarios           []*ScenarioTemplate `protobuf:"bytes,7,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NodeArchetype) Reset() {
	*x = NodeArchetype{}
	mi := &file_src_lib_simulation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeArchetype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeArchetype) ProtoMessage() {}

func (x *NodeArchetype) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_simulation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeArchetype.ProtoReflect.Descriptor instead.
func (*NodeArchetype) Descriptor() ([]byte, []int) {
	return file_src_lib_simulation_proto_rawDescGZIP(), []int{11}
}

func (x *NodeArchetype) GetArchetypeId() string {
	if x != nil {
		return x.ArchetypeId
	}
	return ""
}

func (x *NodeArchetype) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NodeArchetype) GetBaseTempC() float64 {
	if x != nil {
		return x.BaseTempC
	}
	return 0
}

func (x *NodeArchetype) GetInsulationDecayRate() float64 {
	if x != nil {
		return x.InsulationDecayRate
	}
	return 0
}

func (x *NodeArchetype) GetActors() []*ActorTemplate {
	if x != nil {
		return x.Actors
	}
	return nil
}

func (x *NodeArchetype) GetDevices() []*DeviceTemplate {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *NodeArchetype) GetScenarios() []*ScenarioTemplate {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

var File_src_lib_simulation_proto protoreflect.FileDescriptor

const file_src_lib_simulation_proto_rawDesc = "" +
	"\n" +
	"\x18src/lib/simulation.proto\x12\rsimulation.v1\"\x86\x01\n" +
	"\x0fEngineCondition\x12\x1f\n" +
	"\vcontext_key\x18\x01 \x01(\tR\n" +
	"contextKey\x12<\n" +
	"\boperator\x18\x02 \x01(\x0e2 .simulation.v1.ConditionOperatorR\boperator\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\x94\x01\n" +
	"\x14DistributionModifier\x12<\n" +
	"\tcondition\x18\x01 \x01(\v2\x1e.simulation.v1.EngineConditionR\tcondition\x12\x1d\n" +
	"\n" +
	"shift_mean\x18\x02 \x01(\tR\tshiftMean\x12\x1f\n" +
	"\vshift_value\x18\x03 \x01(\tR\n" +
	"shiftValue\"\xf8\x01\n" +
	"\x17ProbabilityDistribution\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.simulation.v1.DistributionTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04mean\x18\x03 \x01(\tR\x04mean\x12\x17\n" +
	"\astd_dev\x18\x04 \x01(\tR\x06stdDev\x12\x10\n" +
	"\x03min\x18\x05 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x06 \x01(\x01R\x03max\x12A\n" +
	"\tmodifiers\x18\a \x03(\v2#.simulation.v1.DistributionModifierR\tmodifiers\"\x94\x01\n" +
	"\vFatigueRule\x12)\n" +
	"\x10lockout_duration\x18\x01 \x01(\tR\x0flockoutDuration\x12+\n" +
	"\x11recovery_duration\x18\x02 \x01(\tR\x10recoveryDuration\x12-\n" +
	"\x12penalty_multiplier\x18\x03 \x01(\x01R\x11penaltyMultiplier\"j\n" +
	"\x0eDeviceTaxonomy\x129\n" +
	"\bcategory\x18\x01 \x01(\x0e2\x1d.simulation.v1.DeviceCategoryR\bcategory\x12\x1d\n" +
	"\n" +
	"class_name\x18\x02 \x01(\tR\tclassName\"\xae\x01\n" +
	"\rDeviceProfile\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.simulation.v1.ProfileTypeR\x04type\x12\x1b\n" +
	"\tmax_watts\x18\x02 \x01(\x01R\bmaxWatts\x12#\n" +
	"\rstandby_watts\x18\x03 \x01(\x01R\fstandbyWatts\x12+\n" +
	"\x11cooldown_duration\x18\x04 \x01(\tR\x10cooldownDuration\"\xbf\x02\n" +
	"\x0eDeviceTemplate\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x129\n" +
	"\btaxonomy\x18\x02 \x01(\v2\x1d.simulation.v1.DeviceTaxonomyR\btaxonomy\x12J\n" +
	"\tspecifics\x18\x03 \x03(\v2,.simulation.v1.DeviceTemplate.SpecificsEntryR\tspecifics\x12K\n" +
	"\x12electrical_profile\x18\x04 \x01(\v2\x1c.simulation.v1.DeviceProfileR\x11electricalProfile\x1a<\n" +
	"\x0eSpecificsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x02\n" +
	"\aTrigger\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.simulation.v1.TriggerTypeR\x04type\x12J\n" +
	"\fdistribution\x18\x02 \x01(\v2&.simulation.v1.ProbabilityDistributionR\fdistribution\x12G\n" +
	"\x0fbase_conditions\x18\x03 \x03(\v2\x1e.simulation.v1.EngineConditionR\x0ebaseConditions\x12=\n" +
	"\ffatigue_rule\x18\x04 \x01(\v2\x1a.simulation.v1.FatigueRuleR\vfatigueRule\"\xbf\x02\n" +
	"\x0eScenarioAction\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x120\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1a.simulation.v1.DeviceStateR\x05state\x12(\n" +
	"\x10delay_from_start\x18\x03 \x01(\tR\x0edelayFromStart\x12M\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2-.simulation.v1.ScenarioAction.ParametersEntryR\n" +
	"parameters\x1ae\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.simulation.v1.ProbabilityDistributionR\x05value:\x028\x01\"\xb9\x01\n" +
	"\x10ScenarioTemplate\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x120\n" +
	"\atrigger\x18\x03 \x01(\v2\x16.simulation.v1.TriggerR\atrigger\x127\n" +
	"\aactions\x18\x04 \x03(\v2\x1d.simulation.v1.ScenarioActionR\aactions\">\n" +
	"\rActorTemplate\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\xd6\x02\n" +
	"\rNodeArchetype\x12!\n" +
	"\farchetype_id\x18\x01 \x01(\tR\varchetypeId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\vbase_temp_c\x18\x03 \x01(\x01R\tbaseTempC\x122\n" +
	"\x15insulation_decay_rate\x18\x04 \x01(\x01R\x13insulationDecayRate\x124\n" +
	"\x06actors\x18\x05 \x03(\v2\x1c.simulation.v1.ActorTemplateR\x06actors\x127\n" +
	"\adevices\x18\x06 \x03(\v2\x1d.simulation.v1.DeviceTemplateR\adevices\x12=\n" +
	"\tscenarios\x18\a \x03(\v2\x1f.simulation.v1.ScenarioTemplateR\tscenarios*\x92\x01\n" +
	"\x10DistributionType\x12!\n" +
	"\x1dDISTRIBUTION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DISTRIBUTION_TYPE_NORMAL\x10\x01\x12\x1d\n" +
	"\x19DISTRIBUTION_TYPE_UNIFORM\x10\x02\x12\x1e\n" +
	"\x1aDISTRIBUTION_TYPE_CONSTANT\x10\x03*\xdc\x01\n" +
	"\x11ConditionOperator\x12\"\n" +
	"\x1eCONDITION_OPERATOR_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CONDITION_OPERATOR_EQ\x10\x01\x12\x1a\n" +
	"\x16CONDITION_OPERATOR_NEQ\x10\x02\x12\x19\n" +
	"\x15CONDITION_OPERATOR_GT\x10\x03\x12\x19\n" +
	"\x15CONDITION_OPERATOR_LT\x10\x04\x12\x1a\n" +
	"\x16CONDITION_OPERATOR_GTE\x10\x05\x12\x1a\n" +
	"\x16CONDITION_OPERATOR_LTE\x10\x06*\x8e\x02\n" +
	"\x0eDeviceCategory\x12\x1f\n" +
	"\x1bDEVICE_CATEGORY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DEVICE_CATEGORY_COOKING\x10\x01\x12\x1b\n" +
	"\x17DEVICE_CATEGORY_HEATING\x10\x02\x12 \n" +
	"\x1cDEVICE_CATEGORY_COLD_STORAGE\x10\x03\x12\x1c\n" +
	"\x18DEVICE_CATEGORY_LIGHTING\x10\x04\x12!\n" +
	"\x1dDEVICE_CATEGORY_WET_APPLIANCE\x10\x05\x12\x1f\n" +
	"\x1bDEVICE_CATEGORY_ELECTRONICS\x10\x06\x12\x1d\n" +
	"\x19DEVICE_CATEGORY_BASE_LOAD\x10\a*z\n" +
	"\vProfileType\x12\x1c\n" +
	"\x18PROFILE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PROFILE_TYPE_CONSTANT\x10\x01\x12\x17\n" +
	"\x13PROFILE_TYPE_CYCLIC\x10\x02\x12\x19\n" +
	"\x15PROFILE_TYPE_VARIABLE\x10\x03*j\n" +
	"\vTriggerType\x12\x1c\n" +
	"\x18TRIGGER_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TRIGGER_TYPE_TIME_OF_DAY\x10\x01\x12\x1f\n" +
	"\x1bTRIGGER_TYPE_EVENT_REACTION\x10\x02*p\n" +
	"\vDeviceState\x12\x1c\n" +
	"\x18DEVICE_STATE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fDEVICE_STATE_ON\x10\x01\x12\x14\n" +
	"\x10DEVICE_STATE_OFF\x10\x02\x12\x18\n" +
	"\x14DEVICE_STATE_STANDBY\x10\x03B=Z;github.com/tinywideclouds/gen-sim/libs/schema/simulation/v1b\x06proto3"

var (
	file_src_lib_simulation_proto_rawDescOnce sync.Once
	file_src_lib_simulation_proto_rawDescData []byte
)

func file_src_lib_simulation_proto_rawDescGZIP() []byte {
	file_src_lib_simulation_proto_rawDescOnce.Do(func() {
		file_src_lib_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_lib_simulation_proto_rawDesc), len(file_src_lib_simulation_proto_rawDesc)))
	})
	return file_src_lib_simulation_proto_rawDescData
}

var file_src_lib_simulation_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_src_lib_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_src_lib_simulation_proto_goTypes = []any{
	(DistributionType)(0),           // 0: simulation.v1.DistributionType
	(ConditionOperator)(0),          // 1: simulation.v1.ConditionOperator
	(DeviceCategory)(0),             // 2: simulation.v1.DeviceCategory
	(ProfileType)(0),                // 3: simulation.v1.ProfileType
	(TriggerType)(0),                // 4: simulation.v1.TriggerType
	(DeviceState)(0),                // 5: simulation.v1.DeviceState
	(*EngineCondition)(nil),         // 6: simulation.v1.EngineCondition
	(*DistributionModifier)(nil),    // 7: simulation.v1.DistributionModifier
	(*ProbabilityDistribution)(nil), // 8: simulation.v1.ProbabilityDistribution
	(*FatigueRule)(nil),             // 9: simulation.v1.FatigueRule
	(*DeviceTaxonomy)(nil),          // 10: simulation.v1.DeviceTaxonomy
	(*DeviceProfile)(nil),           // 11: simulation.v1.DeviceProfile
	(*DeviceTemplate)(nil),          // 12: simulation.v1.DeviceTemplate
	(*Trigger)(nil),                 // 13: simulation.v1.Trigger
	(*ScenarioAction)(nil),          // 14: simulation.v1.ScenarioAction
	(*ScenarioTemplate)(nil),        // 15: simulation.v1.ScenarioTemplate
	(*ActorTemplate)(nil),           // 16: simulation.v1.ActorTemplate
	(*NodeArchetype)(nil),           // 17: simulation.v1.NodeArchetype
	nil,                             // 18: simulation.v1.DeviceTemplate.SpecificsEntry
	nil,                             // 19: simulation.v1.ScenarioAction.ParametersEntry
}
var file_src_lib_simulation_proto_depIdxs = []int32{
	1,  // 0: simulation.v1.EngineCondition.operator:type_name -> simulation.v1.ConditionOperator
	6,  // 1: simulation.v1.DistributionModifier.condition:type_name -> simulation.v1.EngineCondition
	0,  // 2: simulation.v1.ProbabilityDistribution.type:type_name -> simulation.v1.DistributionType
	7,  // 3: simulation.v1.ProbabilityDistribution.modifiers:type_name -> simulation.v1.DistributionModifier
	2,  // 4: simulation.v1.DeviceTaxonomy.category:type_name -> simulation.v1.DeviceCategory
	3,  // 5: simulation.v1.DeviceProfile.type:type_name -> simulation.v1.ProfileType
	10, // 6: simulation.v1.DeviceTemplate.taxonomy:type_name -> simulation.v1.DeviceTaxonomy
	18, // 7: simulation.v1.DeviceTemplate.specifics:type_name -> simulation.v1.DeviceTemplate.SpecificsEntry
	11, // 8: simulation.v1.DeviceTemplate.electrical_profile:type_name -> simulation.v1.DeviceProfile
	4,  // 9: simulation.v1.Trigger.type:type_name -> simulation.v1.TriggerType
	8,  // 10: simulation.v1.Trigger.distribution:type_name -> simulation.v1.ProbabilityDistribution
	6,  // 11: simulation.v1.Trigger.base_conditions:type_name -> simulation.v1.EngineCondition
	9,  // 12: simulation.v1.Trigger.fatigue_rule:type_name -> simulation.v1.FatigueRule
	5,  // 13: simulation.v1.ScenarioAction.state:type_name -> simulation.v1.DeviceState
	19, // 14: simulation.v1.ScenarioAction.parameters:type_name -> simulation.v1.ScenarioAction.ParametersEntry
	13, // 15: simulation.v1.ScenarioTemplate.trigger:type_name -> simulation.v1.Trigger
	14, // 16: simulation.v1.ScenarioTemplate.actions:type_name -> simulation.v1.ScenarioAction
	16, // 17: simulation.v1.NodeArchetype.actors:type_name -> simulation.v1.ActorTemplate
	12, // 18: simulation.v1.NodeArchetype.devices:type_name -> simulation.v1.DeviceTemplate
	15, // 19: simulation.v1.NodeArchetype.scenarios:type_name -> simulation.v1.ScenarioTemplate
	8,  // 20: simulation.v1.ScenarioAction.ParametersEntry.value:type_name -> simulation.v1.ProbabilityDistribution
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_src_lib_simulation_proto_init() }
func file_src_lib_simulation_proto_init() {
	if File_src_lib_simulation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_lib_simulation_proto_rawDesc), len(file_src_lib_simulation_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_lib_simulation_proto_goTypes,
		DependencyIndexes: file_src_lib_simulation_proto_depIdxs,
		EnumInfos:         file_src_lib_simulation_proto_enumTypes,
		MessageInfos:      file_src_lib_simulation_proto_msgTypes,
	}.Build()
	File_src_lib_simulation_proto = out.File
	file_src_lib_simulation_proto_goTypes = nil
	file_src_lib_simulation_proto_depIdxs = nil
}
